on: [status]
jobs:
  circleci_artifacts_redirector_job:
    # Don't run Action on forks, and allow skipping CI
    if: "github.repository == 'data-apis/array-api' && !contains(github.event.head_commit.message, '[ci skip]') && !contains(github.event.head_commit.message, '[skip ci]') && !contains(github.event.head_commit.message, '[skip github]')"
    runs-on: ubuntu-latest
    name: Run CircleCI artifacts redirector
    steps:
      - name: GitHub Action step
        id: step1
        uses: larsoner/circleci-artifacts-redirector-action@master
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          artifact-path: 0/build/latest/index.html
          circleci-jobs: build_page
          job-title: Check the rendered docs here!
      - name: Array API preview
        run: |
          curl --fail ${{ steps.step1.outputs.url }} | grep $GITHUB_SHA
